### ISSUE TITLE
Add to tinted-theming/schemes

### ISSUE THREAD

**Issue by connorjs** [precious-themes/base16-precious-schemes#1]
Hello there @4lex4 👋🏻,

I would like to add the precious theme base 16 palettes to <https://github.com/tinted-theming/schemes> so that they exist in that ecosystem (example: Vim/Neo-vim via <https://github.com/tinted-theming/base16-vim>).

See the tinted-theming organization page (<https://github.com/tinted-theming>) for more information as needed.

Do you have any concerns with me adding the themes you’ve built there? I plan to keep your YAML files as-is, minus any minor spec changes (example: `palette` nested object). You will remain the author.

I do not expect any support effort from you. If a future user of that ecosystem desires synchronization, then they can update it (like I am doing now).

Cheers,
Connor

**Comment by connorjs** [comment]
I have prepared the commit (<https://github.com/connorjs/schemes/commit/41a58f681e13fd855fc627275e3de1f9166f9874>) in my fork of the repo. I would like your approval, mostly because this base 16 repo does not have a license (although the others have ISC).

**Comment by 4lex4** [comment]
Use it as you wish, it is public domain. I just do not think a bunch of yaml files needs a license.

**Comment by connorjs** [comment]
Thank you! Doubly so for the quick reply.
